int32 body_id
float64 tiempo

#Joints
geometry_msgs/Point32 joint_position_head		#1
geometry_msgs/Point32 joint_position_neck		#2
geometry_msgs/Point32 joint_position_shoulder		#3
geometry_msgs/Point32 joint_position_spine_top	#4
geometry_msgs/Point32 joint_position_spine_mid	#5
geometry_msgs/Point32 joint_position_spine_bottom	#6

geometry_msgs/Point32 joint_position_left_shoulder	#7
geometry_msgs/Point32 joint_position_left_elbow	#8
geometry_msgs/Point32 joint_position_left_hand	#9

geometry_msgs/Point32 joint_position_right_shoulder	#10
geometry_msgs/Point32 joint_position_right_elbow	#11
geometry_msgs/Point32 joint_position_right_hand	#12

geometry_msgs/Point32 joint_position_right_hip	#13
geometry_msgs/Point32 joint_position_right_knee	#14
geometry_msgs/Point32 joint_position_right_ankle	#15

geometry_msgs/Point32 joint_position_left_hip		#16
geometry_msgs/Point32 joint_position_left_knee	#17
geometry_msgs/Point32 joint_position_left_ankle	#18
