# map_server_params.yaml
map_server:
    ros__parameters:
        frame_id: map
        topic_name: map
        use_sim_time: false
        yaml_filename: /home/robogait/catkin_ws/src/pkg_navigation/maps/test_map.yaml
